trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: echo "Building the project..."
    displayName: "Build Step"
  - script: echo "Running tests..."
    displayName: "Test Step"
