name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      name:
        description: 'Name of the application to build'
        required: true
        type: string
      os:
        description: 'Operating system to run on'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  build:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build ${{ inputs.name }}
        run: echo "Building ${{ inputs.name }}..."
        
      - name: Test ${{ inputs.name }}
        run: echo "Testing ${{ inputs.name }}..."